### ISSUE TITLE
IE Dom Problem

### ISSUE THREAD

**Issue by Haythem** [Amphiluke/handy-scroll#1]
On Internet Explorer (11 & 10), the browser can't interpret the `dom` object located in `src/dom.js` because it does not respect the format `key : value` for properties throwing the following error :
`SCRIPT1003: Expected ':'`

The problem occurs only when importing the handy scroll module not the minified version because the latter has been already transpiled.

**Comment by Amphiluke** [comment]
Hi, @Haythem

Could you please explain which way do you import raw module sources in IE? Since IE doesn’t support syntax of ES 2015, transpiled version is the only way to use the widget in this browser. Of course, you may transpile the sources on your own, but nevertheless transpiling step is required to make things work in IE.

**Comment by Haythem** [comment]
Hey @Amphiluke,
First of all, thanks for your reactivity.

In fact, I have an Angular v6.x application and I'm importing the `handy-scroll` module in one of my directives.

```typescript
import { Directive, ElementRef, NgZone, AfterViewInit, AfterViewChecked } from '@angular/core';

import handyScroll from 'handy-scroll';

/**
 * Floating horizontal scroll bar.
 *
 * @export
 * @class FloatingScrollDirective
 */
@Directive({
  selector: '[floatingScroll]'
})
export class FloatingScrollDirective implements AfterViewInit, AfterViewChecked {

  /**
   * Creates an instance of FloatingScrollDirective.
   * @param {ElementRef} element Directive element.
   * @param {NgZone} zone Angular zone.
   * @memberof FloatingScrollDirective
   */
  constructor(private element: ElementRef, private zone: NgZone) { }

  public ngAfterViewInit(): void {
    this.zone.runOutsideAngular(() => handyScroll.mount(this.element.nativeElement));
  }

  public ngAfterViewChecked(): void {
    this.zone.runOutsideAngular(() => handyScroll.update(this.element.nativeElement));
  }
}
```
And since my application is being transpiled to `es5`, the transpiled code preserves the short handed property `doc` in `dom.js`.

**Comment by Amphiluke** [comment]
Yep, it looks like Angular’s command line tools [don’t transpile imported third-party modules](https://github.com/angular/angular-cli/issues/11892#issuecomment-413242740).

Unfortunately, I’m not an expert in Angluar, but it seems that there is yet another solution. One may explicitly specify the path to the transpiled version of the module in `tsconfig.json`. Something like that follows:

```json
{
  "compilerOptions": {
    ..................
    "paths": {
      "handy-scroll": [
        "../node_modules/handy-scroll/dist/handy-scroll.js"
      ]
    }
  }
}
```

By default, the module will be included in your bundle as a CommonJS module. So, you will import it in your directive as follows:

```javascript
import * as handyScroll from 'handy-scroll';
```

At least in this case you don’t need to expose any variables to global namespace.

**Comment by Haythem** [comment]
@Amphiluke, I've managed to get it working with similar solution.

`angular.json`
```json
"scripts": [
  "node_modules/handy-scroll/dist/handy-scroll.min.js"
]
```
And then in my directive :
`declare var handyScroll: any;`

Thanks anyway. I'm closing this issue.
