### ISSUE TITLE
How will it work in React JS with materialUI table

### ISSUE THREAD

**Issue by sga-harshita** [Amphiluke/handy-scroll#12]

**Comment by Amphiluke** [comment]
Hello

The widget handy-scroll is not designed for the React ecosystem. Nevertheless, it’s not too difficult to wrap the widget in a simple React component. You can find a comprehensive guide in the [official docs](https://reactjs.org/docs/integrating-with-other-libraries.html). I’m not a React user but here is the [simplest demo](https://codepen.io/amphiluke/pen/vYmMEJV?editors=0010) I’ve built based on this guide.
