### ISSUE TITLE
autoInit issue with SSR

### ISSUE THREAD

**Issue by benatkin** [Amphiluke/handy-scroll#13]
When using Next.js, I get an error that `document` is undefined, from the server side rendering, unless I do a dynamic import.

It would be more convenient if it waited until a method was called until it accessed `document`, and skipped `autoInit` if `typeof window === 'undefined'`.

**Comment by benatkin** [comment]
I have a fairly good way for it to work with [Next.js](https://nextjs.org/):

##### `DataTable.js`

```js
import { forwardRef, useImperativeHandle, useRef, useState } from 'react'
import {
  Box,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TablePagination,
  TableRow,
} from '@material-ui/core'
import { makeStyles } from '@material-ui/styles'
import dynamic from 'next/dynamic'

const HandyScroll = dynamic(() => import('./HandyScroll'), { ssr: false })

const useStyles = makeStyles((theme) => ({
  paper: {
    width: '100%',
    display: 'flex',
    marginTop: theme.spacing(3),
    marginBottom: theme.spacing(3),
  },
  wrap: {
    flexGrow: 1,
    overflow: 'auto',
  },
}))

function DataTable({ columns, rows }, ref) {
  const classes = useStyles()
  const scrollRef = useRef()
  const [page, setPage] = useState(0)
  useImperativeHandle(ref, () => ({
    resetPage() {
      setPage(0)
    }
  }))
  return (
    <Paper className={classes.paper}>
      <Box className={classes.wrap} ref={scrollRef}>
        <Table>
          <HandyScroll scrollRef={scrollRef} />
          <TableHead>
            <TableRow>
              {columns.map((column) => {
                const { name, headerComponent: Header } = column
                return <Header key={name} column={column} />
              })}
            </TableRow>
          </TableHead>
          <TableBody>
            {rows.map((row) => (
              <TableRow key={row.id}>
                {columns.map((column) => {
                  const { name, valueComponent: Value } = column
                  return <Value key={name} row={row} column={column} />
                })}
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </Box>
    </Paper>
  )
}

export default forwardRef(DataTable)
```

##### `HandyScroll.js`

```js
import { useEffect } from 'react'
import handyScroll from 'handy-scroll'

function HandyScroll({scrollRef}) {
  useEffect(async () => {
    if (scrollRef.current) {
      if (handyScroll) {
        handyScroll.mount(scrollRef.current)
      }
    }
    return async () => {
      if (handyScroll) {
        handyScroll.destroy(scrollRef.current)
      }
    }
  }, [scrollRef.current])
  return null
}

export default HandyScroll
```

**Comment by Amphiluke** [comment]
Hello, Benjamin!

Thank you for your suggestion. I’ve made the changes you mentioned, currently in the branch `ssr-fixes`. Could you please try installing the updated package from this branch and check if everything works correctly in your environment?
```
npm install --save github:Amphiluke/handy-scroll#ssr-fixes
```
I tested by myself as well, and found no issues, but it would be great if you confirmed too before I publish the new version to npm.

**Comment by benatkin** [comment]
Awesome. Thanks.

I just confirmed it works! I installed the branch and replaced the dynamic import with just checking for `if (typeof window !== 'undefined')` before calling `handyScroll.mount()` and there were no errors and handy-scroll still works.

**Comment by Amphiluke** [comment]
> just checking for `if (typeof window !== 'undefined')` before calling `handyScroll.mount()`

That’s strange. In my tests, everything worked without additional conditions; existing checks in the sources of handy-scroll were enough. I replaced the dynamic import with a static one, and used the effect hook similar to that in your example. The method `useEffect` isn’t invoked while building for SSR, so `handyScroll.mount()` shouldn’t throw.

Anyway, the new patch version (1.0.6) is now published on npm. I’m closing the issue. Thank you for your contribution :)

**Comment by benatkin** [comment]
@Amphiluke ah, I see. I hadn't tried removing `typeof window !== 'undefined'` but it would work because I was calling it inside of `useEffect()`. Thanks for pointing that out.

You're welcome.
