### ISSUE TITLE
Error when instance is destroyed after focusin event fires

### ISSUE THREAD

**Issue by Narretz** [Amphiluke/handy-scroll#14]
Hi,

first of all, I want to say thanks for this lib, it works really well! 

I found a small problem:
The event listener for focusin syncs the widget after a setTimeout: 

https://github.com/Amphiluke/handy-scroll/blob/422e9a6ff3afb033a5e613184d5fb029a312011d/src/handy-scroll-proto.js#L68-L70

This causes an error when the destroy() method is called immediately after the focusin event is fired. syncWidget tries to access an instance container that no longer exists.

In normal circumstances this is unlikely to happen, but in automated tests that fire events very quickly, it does happen.

See this codepen https://codepen.io/narretz/pen/QWgoGJL
Open the browser devtools console and you'll see the error.

**Comment by Amphiluke** [comment]
Hi! You are right, thank you for the finding. :+1: I will publish a fix in a few days

**Comment by Amphiluke** [comment]
The issue has been fixed in the new version of the widget: 1.1.0 (already available on npm).

**Comment by Narretz** [comment]
That was quick! Thanks a lot!
