### ISSUE TITLE
Issue Destroying HandyScroll Elements when Widget Already Removed

### ISSUE THREAD

**Issue by samharvey44** [Amphiluke/handy-scroll#24]
Hi there,
      
Firstly, thanks for this really 'handy 😉' package - such a simple tool really improves UX!

I am using this package within a business application that is utilising 'Laravel Livewire' - essentially a tool designed to work with the 'Laravel' PHP framework that keeps the front and back-end in sync reactively. https://livewire.laravel.com/

Laravel Livewire rebuilds the DOM between requests, and does not recognise the handy-scroll elements as they are added post-mount (after Livewire's last 'capture' of the DOM), therefore removing them from the page on the next rebuild without handy-scroll actually knowing. This is fine - an event listener can be added to simply destroy and re-mount all handy-scroll elements when Livewire does its rebuilds.
However, this is currently not possible, as an error is thrown within the below code due to `parentNode` being null, since it's already been removed without handy-scroll knowing. 

I suggest that null coalescence is added before invoking `removeChild` in the below snippet, to make sure that the `parentNode` actually exists.
I know this would never be an issue for 99% of cases, only if you are using a package that is mutating the DOM in the way that Livewire is for my case - however, I think it would add more flexibility, as it resolves cases such as this without any drawbacks.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/handy-scroll/src/handy-scroll-proto.js b/node_modules/handy-scroll/src/handy-scroll-proto.js
index c521ad0..2acd4f4 100644
--- a/node_modules/handy-scroll/src/handy-scroll-proto.js
+++ b/node_modules/handy-scroll/src/handy-scroll-proto.js
@@ -145,7 +145,7 @@ let handyScrollProto = {
         instance.eventHandlers.forEach(({el, handlers}) => {
             Object.keys(handlers).forEach(event => el.removeEventListener(event, handlers[event], false));
         });
-        instance.widget.parentNode.removeChild(instance.widget);
+        instance.widget.parentNode?.removeChild(instance.widget);
         instance.eventHandlers = instance.widget = instance.container = instance.scrollBody = null;
     }
 };
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by Amphiluke** [comment]
Hi,

Thank you for this finding! It’s definitely worth fixing this bug. I suppose, we can safely refactor this line using the `Element.remove()` method as it’s currently widely supported in all browsers.

**Comment by Amphiluke** [comment]
The patch (v1.1.5) is published on npm.
Thank you for your contribution! :+1:

**Comment by samharvey44** [comment]
Can confirm this is working great now. Thank you! 🥳
