### ISSUE TITLE
how use in vuejs ? 

### ISSUE THREAD

**Issue by khanhnam99** [Amphiluke/handy-scroll#4]
npm i floating-scroll

------------------------
import floating-scroll from "floating-scroll";

how use it  in  html?

i use es6

**Comment by khanhnam99** [comment]
thanks

**Comment by khanhnam99** [comment]
<template>
<div class="my-container" ref="scrollable">
   <p>this is demo</p>
<p>this is demo</p>


</div>
</template>

<script>
    import handyScroll from 'handy-scroll';

    export default {
        name: "Worker",
        data() {
            return {} 
        },
        mounted() {
            this.$nextTick(() => {
                handyScroll.mount(this.$refs.scrollable);
            });

**Comment by Amphiluke** [comment]
The component [`vue-handy-scroll`](https://github.com/Amphiluke/vue-handy-scroll) has finally been published on npm. It is a fully Vue-oriented analog of the handy-scroll widget. You may start using this component if integration of the Vanilla JS solution is undesirable for you.
