### ISSUE TITLE
not scroll handyScroll  in vuejs

### ISSUE THREAD

**Issue by khanhnam99** [Amphiluke/handy-scroll#5]
<template>
<div class="my-container" ref="scrollable">
   <p>this is demo</p>
   <p>this is demo</p>
<p>this is demo</p>
<p>this is demo</p>
<p>this is demo</p>
<p>this is demo</p>
<p>this is demo</p>
<p>this is demo</p>
<p>this is demo</p>
<p>this is demo</p>
<p>this is demo</p>
<p>this is demo</p>
</div>
</template>

<script>
    import handyScroll 

from 'handy-scroll';

    export default {
        name: "Worker",
        data() {
            return {} 
        },
        mounted() {
            this.$nextTick(() => {
                handyScroll.mount(this.$refs.scrollable);
            });
</script>

![Capture2](https://user-images.githubusercontent.com/575720/70020081-2495fb80-15be-11ea-8588-79c705d90b96.PNG)

![Capture](https://user-images.githubusercontent.com/575720/70019557-38d8f900-15bc-11ea-83ae-9672c89fa92c.PNG)

this is my component in vuejs
not scroll
pls help me

**Comment by Amphiluke** [comment]
Hello, @khanhnam99,

Have you added or imported the stylesheet file [handy-scroll.css](https://github.com/Amphiluke/handy-scroll/blob/master/dist/handy-scroll.css) in your app? You may find it in the `dist` sub-directory of the package installation path, i.e. `node_modules/handy-scroll/dist/handy-scroll.css`.

**Comment by khanhnam99** [comment]
thanks
