### ISSUE TITLE
Handy Scroll on IE11 throwing Script 1003 ':' expected

### ISSUE THREAD

**Issue by MirkoWeber** [Amphiluke/handy-scroll#7]
Hi, I imported handyscroll like this:

`import handyScroll from "handy-scroll";`

and mounted it like this:

`handyScroll.mount(".bonus-board-idea-list-table");`

It works perfect, but on IE11 I get Script 1003 ':' expected error, leading 
to other errors which crash my whole client side code on IE 11,

I am using handyscroll with normal JS and Webpack, I installed it via npm install.
Some user said, that he could include the min.js version, but his approaches where all 
angular specific, how would someone go about this using normal JS ?

Thanks for reading.

**Comment by Amphiluke** [comment]
Hello, @MirkoWeber,

The widget’s sources are written using ECMAScript 2015, the syntax that is not supported in IE. If you want to use the widget in IE, you will need to import the [_transpiled_ version](https://github.com/Amphiluke/handy-scroll/blob/master/dist/handy-scroll.min.js) from the `dist` directory.

So try importing handy-scroll in this way:
```javascript
import handyScroll from "handy-scroll/dist/handy-scroll.min.js";
```

**Comment by MirkoWeber** [comment]
thanks, I give it a try.
Also thank you very much for this splendid library

**Comment by MirkoWeber** [comment]
Works perfectly, closing this now
